baseURL: "https://bobabot.ca"
languageCode: "en-us"
title: "BobaBot"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML]

disableKinds:
  - taxonomy
  - term

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepConditionalComments: false
      keepDefaultAttrVals: false
      keepDocumentTags: false
      keepEndTags: false
      keepWhitespace: false
